function Madrigal= load_pfisr_matfile(year, month, day, kindat)

% Created by V. Sreenivash 2018
% Commented by S. Datta-Barua
% 20 Feb 2019
% 4 Apr 2019 Once V's paper is done, change the file naming convention to
% be yy_mm_dd.mat instead of dd_mm_yy.mat.  Also use datestr to create, so
% you don't have to zero-pad the strings.
%
% This function returns a variable containing the PFISR data for the
% user-specified UT date.  If the .mat file from which it is loaded doesn't
% exist, then the function calls download_madrigal_pfisr.m which calls
% globalIsprint.m to download the data from the website.

data=[];

switch kindat
    case 5950
        kindstr = '';
    case 5951
        kindstr = 'ac';
end

% Check if the matfile already exists.
try
    try
    vaishnavidir = '/data1/home/vsreeni1/';

    load([vaishnavidir, 'Madrigal', kindstr, '_', num2str(day), '_', num2str(month), '_', num2str(year), '.mat']);
    cmdstr = ['Madrigal = Madrigal' kindstr ';'];
    eval(cmdstr);
    catch
        mymatdir = '/data1/home/sdattaba/matfiles/pfisr/';
        load([mymatdir, 'Madrigal', kindstr, '_', datestr(datenum([year, month, day]), 'dd_mm_yyyy'), '.mat']);
    end
% Otherwise extract from the already downloaded text file if it exists, or
% else download from sri.com for the first time, then save.
catch

    datadir = '/Users/seebany/Dropbox/Data/pfisr/';
    %textfile = ['Madrigal' datestr([year, mon, day], 'yymmdd') '.txt'];
    filename = [datadir 'Madrigal13-15.txt'];

    % If the year is 2013-2015 long pulse, then the data were already downloaded by
    % Vaishnavi.
    tic
    if year >= 2014 & year <= 2015 & kindat == 5950
        data=load(filename); %This .txt file is downloaded using the script generated by the Madrigal
    else
        filename = download_madrigal_pfisr(year, month, day, kindat);
        data = load(filename);
    end
    toc

    %Example : Oct 7 2015
    %rows=find(data(:,12)==7&data(:,17)==2015&data(:,19)==10);
    rows=find(data(:,12)==day&data(:,17)==year&data(:,19)==month);

    switch kindat
        case 5950
    %        kindstr = '';
            Madrigal=data(rows,:);
        case 5951
    %        kindstr = 'ac';
            Madrigalac = data(rows,:);
    end

    save(['Madrigal', kindstr, '_',num2str(day),'_',num2str(month),'_', ...
        num2str(year),'.mat'], ...
        ['Madrigal', kindstr]);
end